data:
    dataset: "imagenet"
    root: "data/ImageNet_ILSVRC2012/"
    keep_class: None
    num_workers: 4
    resize_size: 512
    crop_size: 512

train:
    batch_size: 2 #8
    save_steps: 200
    num_train_epochs: 1
    max_train_steps: 600
    gradient_accumulation_steps: 32
    learning_rate: 5.0e-08
    scale_lr: False
    scale_learning_rate: None
    lr_scheduler: "constant"
    lr_warmup_steps: 0
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 1e-2
    adam_epsilon: 1e-08
    load_pretrain_path: "ckpts/pretrains/stable-diffusion-v1-4"
    load_token_path: "ckpts/imagenet/tokens"
    save_path: "ckpts/imagenet"

test:
    batch_size: 2
    eval_mode: "top1" #["gtk", "top1", "top5"]
    cam_thr: 0.25
    combine_ratio: 0.6
    load_class_path: "ckpts/classification/imagenet_efficientnet-b7_3rdparty_8xb32-aa-advprop_in1k.json"
    load_pretrain_path: "ckpts/pretrains/stable-diffusion-v1-4"
    load_token_path: "ckpts/imagenet/tokens/"
    load_unet_path: "ckpts/imagenet/unet/"
    save_vis_path: None
    save_log_path: "ckpts/imagenet/log.txt"



